import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/provider/SmoothScrollprovider";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import TanstackQueryProvider from "@/components/provider/TanstackQueryProvider";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata: Metadata = {
  title: "WOOD TALKS",
  description: "Generated by create next app",
  icons: {
    icon: "/fav.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(figtree.variable)}>
      <body className="font-sans antialiased">
        <NextTopLoader color="#007066" height={3} showSpinner={false} />
        <TanstackQueryProvider>
          <SmoothScrollProvider>{children}</SmoothScrollProvider>
        </TanstackQueryProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
