import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SmoothScrollProvider from "@/components/provider/SmoothScrollprovider";
import NextTopLoader from "nextjs-toploader";

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata: Metadata = {
  title: "WOOD TALKS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(figtree.variable)}>
      <body className="font-sans antialiased">
         <NextTopLoader color="#007066" height={3} showSpinner={false} />
        <SmoothScrollProvider>
          {children}
          </SmoothScrollProvider>
      </body>
    </html>
  );
}
